# Generated by Django 5.2 on 2025-04-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmodule", "0004_course_department_student_courses_student_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("addresses", models.ManyToManyField(to="bookmodule.address2")),
            ],
        ),
    ]
